services:
  # Nginx Service
  nginx:
    container_name: nginx
    build: ./.docker/nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - .:/var/www/core
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d
      - ./.docker/logs/nginx:/var/log/nginx
      - ./.docker/nginx/certs:/etc/nginx/certs
    environment:
      WORKDIR: /var/www/core
      APP_HOST: ${APP_HOST}
      API_HOST: ${API_HOST}
    depends_on:
      php:
        condition: service_started
      scheduler:
        condition: service_started
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      internet:
        aliases:
          - core.local
          - api.core.local
          - admin.core.local

  # PHP Service
  php:
    container_name: php
    build:
      context: ./.docker/php
      args:
        HOST_UID: ${HOST_UID}
        USER_NAME: ${DOCKER_PROJECT_NAME}
        TZ: ${DOCKER_TIMEZONE}
    working_dir: /var/www/core
    restart: unless-stopped
    volumes:
      - .:/var/www/core
      - ./.docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./.docker/php/conf.d/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
      - ./.docker/logs/php:/var/log/php
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      TZ: ${DOCKER_TIMEZONE}
      PHP_MEMORY_LIMIT: "4096M"
    networks:
      - internet
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # Mysql Service
  mysql:
    container_name: mysql
    image: mysql:8.4.3
    environment:
      TZ: ${DOCKER_TIMEZONE}
      MYSQL_ROOT_PASSWORD: ${DOCKER_DB_PASSWORD}
      MYSQL_DATABASE: ${DOCKER_DB_NAME}
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - ./.docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./.docker/logs/mysql:/var/log/mysql
      - ./.docker/mysql/data:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      interval: 5s
      retries: 10
    networks:
      - internet

  # Redis Service
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    restart: unless-stopped
    volumes:
      - ./.docker/redis/data:/var/lib/redis
      - ./.docker/logs/redis:/var/log/redis
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 3
    environment:
      TZ: ${DOCKER_TIMEZONE}
    networks:
      - internet

  # Scheduler Service
  scheduler:
    image: mcuadros/ofelia:latest
    container_name: scheduler
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.docker/scheduler/config.ini:/etc/ofelia/config.ini
    depends_on:
      php:
        condition: service_started
    networks:
      - internet

networks:
  internet:
    name: internet